<?php include 'header.php'; ?>

    <header>
        <div class="StripeBackground">
            <div class="stripe s0"></div>
            <div class="stripe s2 pattern"></div>
        </div>
        <div class="StripeBackground accelerated">
            <div class="stripe s1"></div>
            <div class="stripe s3"></div>
            <div class="stripe s4"></div>
        </div>
        <div class="container">
            <h1 class="title">
                Calculate Your Savings
                <span class="second-line">Learn how to start</span>
            </h1>
            <div class="full">
                <div class="half">
                    <div class="plan">
                        <h2 class="plan-title">70% Average Savings <i class="icon-bulb"></i></h2>
                        <div class="plan-content">
                            <p>Solar photovoltaic (PV) systems – also known as solar panel systems, solar energy systems, or solar power systems – convert sunlight into electricity. You can use the electricity generated by your solar PV system to power your home, your business or even your car.</p>
                            <p>There are many reasons why homeowners go solar, but improving the environment and cutting energy costs are the most common. Many people are aware that solar is a great home efficiency upgrade and are eager to reduce their carbon footprint while also improving property value.</p>
                        </div>
                        <a class="plan-button" href="#">Learn More</a>
                    </div>
                </div>
                <div class="half">
                    <div class="plan">
                        <h2 class="plan-title">Why Choose Solar? <i class="icon-directions"></i></h2>
                        <div class="plan-content">
                            <ul class="list-group">
                                <li class="list-group-item">Drastically reduce or even eliminate your electric bills</li>
                                <li class="list-group-item">Earn a great return on your investment</li>
                                <li class="list-group-item">Protect against rising energy costs</li>
                                <li class="list-group-item">Increase your property value</li>
                                <li class="list-group-item">Boost U.S. energy independence</li>
                                <li class="list-group-item">Create jobs and help your local economy</li>
                                <li class="list-group-item">Protect the environment</li>
                            </ul>
                        </div>
                        <a class="plan-button" href="#">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section id="download" class="download bg-primary text-center">
        <div class="container">
            <div class="full">
                <div class="half">
                    <div class="plan">
                        <h2 class="plan-title">Start Here <i class="icon-location-pin"></i></h2>
                        <div class="plan-content">
                            <ol>
                                <li><strong>Average monthly electric bill:</strong>
                                    <div>
                                        Your power provider usually has this information at the bottom of the bill. If not sum up your last 12 monthly bills and divide by 12.
                                    </div>
                                </li>
                                <li><strong>How much do you plan on spending:</strong>
                                    <div>
                                        Solar panel costs and installations vary based on region. In order for us to create a unique profile for your needs, tell us how much you intend on spending and we can do the hardwork in figuring out what is best for you.
                                    </div>
                                </li>
                                <li><strong>Zip Code:</strong>
                                    <div>
                                        Your zip code helps in determining how much sunlight you get during the day and factors into the efficiency of the solar panels.
                                    </div>
                                </li>
                            </ol>
                        </div>
                        <a class="plan-button" href="#">Learn More</a>
                    </div>
                </div>
                <div class="half">
                    <div class="plan">
                        <h2 class="plan-title">Know your Savings <i class="icon-calculator"></i></h2>
                        <div class="plan-content">
                            <form id="solar-calc" action="results.php" method="post">
                                <div class="form-group">
                                    <label for="utility-bill">Average Monthly Electric Bill</label>
                                    <input type="text" name="utility-bill" value="" class="form-control" placeholder="Avg Utility Bill">
                                    <div class="error"></div>
                                </div>
                                <div class="form-group">
                                    <label for="estimated-cost">How much do you plan on spending? <small>Avg. $15,000</small></label>
                                    <input type="text" name="estimated-cost" value="" class="form-control" placeholder="Estimated Costs">
                                    <div class="error"></div>
                                </div>
                                <div class="form-group">
                                    <label for="zip-code">Zip Code</label>
                                    <input type="text" name="zip-code" value="" class="form-control" placeholder="Zip Code">
                                    <div class="error"></div>
                                </div>
                                <button type="submit" class="btn btn-default">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

<?php include 'footer.php'; ?>